import React from "react";

function BasicButtons({
  handleErase,
  handleClear,
  handleClick,
  calculate,
  numbers,
}) {
  return (
    <div>
      <div className="buttons">
        <div className="display-num__div">
          <input
            disabled="true"
            value={numbers}
            placeholder="0"
            className="display-num"
          ></input>
        </div>
        <input
          type="button"
          value="C"
          onClick={handleErase}
          className="operator"
        ></input>
        <input
          type="button"
          value="Del"
          onClick={handleClear}
          className="operator"
        ></input>
        <input
          type="button"
          value="+"
          onClick={handleClick}
          className="operator"
        ></input>
        <input
          type="button"
          value="-"
          onClick={handleClick}
          className="operator"
        ></input>
        <input
          type="button"
          value="*"
          onClick={handleClick}
          className="operator"
        ></input>
        <input
          type="button"
          value="/"
          onClick={handleClick}
          className="operator"
        ></input>
        <input
          type="button"
          value="7"
          onClick={handleClick}
          className="number"
        ></input>
        <input
          type="button"
          value="8"
          onClick={handleClick}
          className="number"
        ></input>
        <input
          type="button"
          value="9"
          onClick={handleClick}
          className="number"
        ></input>
        <input
          type="button"
          value="4"
          onClick={handleClick}
          className="number"
        ></input>
        <input
          type="button"
          value="5"
          onClick={handleClick}
          className="number"
        ></input>
        <input
          type="button"
          value="6"
          onClick={handleClick}
          className="number"
        ></input>
        <input
          type="button"
          value="1"
          onClick={handleClick}
          className="number"
        ></input>
        <input
          type="button"
          value="2"
          onClick={handleClick}
          className="number"
        ></input>
        <input
          type="button"
          value="3"
          onClick={handleClick}
          className="number"
        ></input>
        <input
          type="button"
          value="."
          onClick={handleClick}
          className="operator"
        ></input>
        <input
          type="button"
          value="="
          onClick={calculate}
          className="operator equals"
        ></input>
      </div>
    </div>
  );
}

export default BasicButtons;
